---

- name: Make sure we have our role path
  local_action: file path={{ galaxy_path }} state=directory

- name: Install roles from galaxy
  local_action: shell test -d {{ galaxy_path }}/{{ item.name }} || ansible-galaxy install {{ item.name }},{{ item.version }} -p {{ galaxy_path }}
  with_items: galaxy_roles
  register: result
  changed_when: "'was installed successfully' in result.stdout"
  when: item.git is not defined

- name: Install roles from git
  local_action: shell test -d {{ galaxy_path }}/{{ item.name }} || ( cd {{ galaxy_path }} && git clone {{ item.git }} -b {{ item.version }} {{ item.name }} )
  with_items: galaxy_roles
  register: result
  changed_when: "'Cloning into' in result.stdout"
  when: item.git is defined
