---

- name: Make sure we have our role path
  local_action: file path={{ galaxy_path }} state=directory

- name: Make sure we have our role version path
  local_action: file path={{ galaxy_versioned_path }} state=directory

- name: Prepare versioned roles
  local_action: shell mkdir -p {{ galaxy_versioned_path }}/{{ item.version }}
  with_items: galaxy_roles
  changed_when: False

- name: Install roles from galaxy
  local_action: shell test -d {{ galaxy_versioned_path }}/{{ item.version }}/{{ item.name }} || ansible-galaxy install {{ item.name }},{{ item.version }} -p {{ galaxy_versioned_path }}/{{ item.version }}
  with_items: galaxy_roles
  register: result
  changed_when: "'was installed successfully' in result.stdout"
  when: item.git is not defined

- name: Install roles from git
  local_action: shell test -d {{ galaxy_versioned_path }}/{{ item.version }}/{{ item.name }} || ( cd {{ galaxy_path }} && git clone {{ item.git }} -b {{ item.version }} {{ galaxy_versioned_path }}/{{ item.version }}/{{ item.name }} )
  with_items: galaxy_roles
  register: result
  changed_when: "'Cloning into' in result.stdout"
  when: item.git is defined

- name: Setup links in role_path
  file:
    src: "{{ galaxy_versioned_path }}/{{ item.version }}/{{ item.name }}"
    dest: "{{ galaxy_path }}/{{ item.name }}"
    state: link
    force: yes
  with_items: galaxy_roles
